[package]
name = "dhcp"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4"
serde = { version = "1.0.215", features = ["derive"] }
bincode = "1.3"
lazy_static = "1.4"
fern = "0.7"
log = "0.4"
humantime = "2.1.0"